Anchor pallet
webb-tools/darkwebb-substrate pull request #6
Opened 2021-08-17 15:33 UTC by drewstone

2021-08-19 12:05 UTC, dev0x1 requested changes

2021-08-19 15:07 UTC, drewstone commented on pallets/mixer/src/lib.rs
> +			<Self as MixerInspector<_,_>>::is_nullifier_used(id, nullifier_hash),
Right, good catch!
```suggestion
			!<Self as MixerInspector<_,_>>::is_nullifier_used(id, nullifier_hash),
```

2021-08-19 15:08 UTC, drewstone commented on pallets/anchor/src/types.rs
> +	fn get_neighbor_roots(id: T::TreeId) -> Result<Vec<T::Element>, dispatch::DispatchError>;	/// Checks if a merkle root is in a tree's cached history or returns
Probably line break needed, will check again.

2021-08-19 15:08 UTC, drewstone commented on pallets/mixer/src/lib.rs
> +		T::Tree::create(T::AccountId::default(), 32u8)
I think I rather meant to use the passed in depth here.
```suggestion
		T::Tree::create(T::AccountId::default(), depth)
```

2021-08-19 15:14 UTC, drewstone commented on pallets/verifier/Cargo.toml
> +ark-crypto-primitives = { version = "^0.3.0", features = ["r1cs"], default-features = false }
Perhaps but it is likely we will stick with these SNARKs for now.

2021-08-19 17:22 UTC, dev0x1 approved these changes

2021-08-20 12:28 UTC, shekohex approved these changes

2021-08-20 14:45 UTC, merged